# The Docker image that will be used to build your app
image:
  name: dock.mau.dev/andreijiroh-dev/docker-images/mkdocs-material:latest

stages:
  - test
  - build
  - sync-repo

default:
  tags:
    - amd64 # currently, we only the image in amd64 right now.
  # Functions that should be executed before the build script is run
  before_script:
    - pipenv install --ignore-pipfile --deploy
    - corepack enable && yarn install
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

# Global builds and stuff
variables:
  DEBUG: "1" # MAY HORRIBLY LEAK SECRETS, PROCEED WITH CAUTION
  FF_ENABLE_COMMIT_DATA: "true"
  FF_GENERATE_SOCIAL_CARDS: "true"
  SECURE_FILES_DOWNLOAD_PATH: .secretskit
  GIT_DEPTH: "0"

pages:
  environment:
    name: production
    url: https://wiki.andreijiroh.xyz
  stage: build
  script:
    - pipenv run build
    - doppler run -- npx wrangler pages deploy --branch "${CI_DEFAULT_BRANCH}" --project-name ajhalili2006-garden public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  variables:
    CF_PAGES_PROJECT_NAME: ajhalili2006
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
